name: Doc Sync

on:
  push:
    branches: [ main ]
    paths:
      - 'doc/**'

env:
  TOKEN: ${{ secrets.TOKEN }}

jobs:
  sync:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '16.x'
    - run: npm install && node doc-repo-push.js
