name: Release
'on':
  push:
    branches:
      - main
    paths:
      - src/**
      - .github/workflows/Release.yml
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 24
          cache: npm
      - run: npm install
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: false
          tag_name: v5.1.6
          name: 5.1.6
          body: "- 修复：更新链接文件不存在(#75)\r\n- 优化：样式优化"
          files: |-
            dist/auto-task.user.js
            dist/auto-task.min.user.js
            dist/auto-task.compatibility.user.js
            dist/auto-task.all.user.js
            dist/auto-task.min.all.user.js
            dist/auto-task.compatibility.all.user.js
          token: ${{ github.TOKEN }}
